# Data Visualization

In [20]:
import pandas as pd
from palmerpenguins import load_penguins_raw
# Load the dataset
df = load_penguins_raw()

### Data Investigation: Initial Overview

Let's start by displaying the first few rows of the DataFrame to get a glimpse of the data, its columns, and the format.

In [21]:
display(df.head())

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN

Next, we'll check the DataFrame's information, which includes the column names, non-null counts, and data types. This helps us understand the structure and identify potential issues like incorrect data types or columns with many missing values.

In [22]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   studyName            344 non-null    str
 1   Sample Number        344 non-null    int64
 2   Species              344 non-null    str
 3   Region               344 non-null    str
 4   Island               344 non-null    str
 5   Stage                344 non-null    str
 6   Individual ID        344 non-null    str
 7   Clutch Completion    344 non-null    str
 8   Date Egg             344 non-null    str
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  333 non-null    str
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    float64
 16  Comments             54 non-null     str
dtypes: float64(6), int64(1), str(10)
memory usage: 79.8 KB
None

Finally, let's count the number of missing values for each column. This is crucial for deciding how to handle missing data during preprocessing.

In [23]:
print(df.isnull().sum())

studyName                0
Sample Number            0
Species                  0
Region                   0
Island                   0
Stage                    0
Individual ID            0
Clutch Completion        0
Date Egg                 0
Culmen Length (mm)       2
Culmen Depth (mm)        2
Flipper Length (mm)      2
Body Mass (g)            2
Sex                     11
Delta 15 N (o/oo)       14
Delta 13 C (o/oo)       13
Comments               290
dtype: int64

Based on the high number of missing values, the 'Comments' column is not very useful and can be dropped.

In [24]:
# Drop the 'Comments' column due to a high number of missing values
df = df.drop('Comments', axis=1)

# Display the number of missing values after dropping 'Comments'
print(df.isnull().sum())

studyName               0
Sample Number           0
Species                 0
Region                  0
Island                  0
Stage                   0
Individual ID           0
Clutch Completion       0
Date Egg                0
Culmen Length (mm)      2
Culmen Depth (mm)       2
Flipper Length (mm)     2
Body Mass (g)           2
Sex                    11
Delta 15 N (o/oo)      14
Delta 13 C (o/oo)      13
dtype: int64

Now, let's address the remaining missing values.

For numerical features like 'Culmen Length (mm)', 'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)', 'Delta 15 N (o/oo)', and 'Delta 13 C (o/oo)', we can impute the missing values with the mean or median. Given the small number of missing values for some of these, the mean is a reasonable choice.

For the categorical feature 'Sex', we will impute the missing values with the mode (the most frequent value).

In [25]:
# Impute numerical columns with the mean
numerical_cols = ['Culmen Length (mm)', 'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)', 'Delta 15 N (o/oo)', 'Delta 13 C (o/oo)']
for col in numerical_cols:
    df[col].fillna(df[col].mean(), inplace=True)

# Impute 'Sex' column with the mode
df['Sex'].fillna(df['Sex'].mode()[0], inplace=True)

# Display the number of missing values after imputation
print(df.isnull().sum())

studyName               0
Sample Number           0
Species                 0
Region                  0
Island                  0
Stage                   0
Individual ID           0
Clutch Completion       0
Date Egg                0
Culmen Length (mm)      2
Culmen Depth (mm)       2
Flipper Length (mm)     2
Body Mass (g)           2
Sex                    11
Delta 15 N (o/oo)      14
Delta 13 C (o/oo)      13
dtype: int64

C:\Users\Thao Vy\AppData\Local\Temp\ipykernel_33968\3001037133.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].mean(), inplace=True)
C:\Users\Thao Vy\AppData\Local\Temp\ipykernel_33968\3001037133.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Sex'].fillna(df['Sex'].mode()[0], inplace=True)

Now that we've handled all missing values, the dataset is cleaner. Let's confirm the data types and look at some summary statistics.

In [26]:
print(df.info())
display(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   studyName            344 non-null    str
 1   Sample Number        344 non-null    int64
 2   Species              344 non-null    str
 3   Region               344 non-null    str
 4   Island               344 non-null    str
 5   Stage                344 non-null    str
 6   Individual ID        344 non-null    str
 7   Clutch Completion    344 non-null    str
 8   Date Egg             344 non-null    str
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  333 non-null    str
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    float64
dtypes: float64(6), int64(1), str(9)
memory usage: 75.1 KB
None

,Sample Number,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Delta 15 N (o/oo),Delta 13 C (o/oo)
count,344.000000,342.000000,342.000000,342.000000,342.000000,330.000000,331.000000
mean,63.151163,43.921930,17.151170,200.915205,4201.754386,8.733382,-25.686292
std,40.430199,5.459584,1.974793,14.061714,801.954536,0.551770,0.793961
min,1.000000,32.100000,13.100000,172.000000,2700.000000,7.632200,-27.018540
25%,29.000000,39.225000,15.600000,190.000000,3550.000000,8.299890,-26.320305
50%,58.000000,44.450000,17.300000,197.000000,4050.000000,8.652405,-25.833520
75%,95.250000,48.500000,18.700000,213.000000,4750.000000,9.172123,-25.062050
max,152.000000,59.600000,21.500000,231.000000,6300.000000,10.025440,-23.787670

We must also check for duplicated values (if there exist any).

In [27]:
print("Number of duplicates:", df.duplicated().sum())

Number of duplicates: 0

Now that missing values are handled and we have an overview of the data types, let's investigate the unique values in the categorical columns. This will help us understand the distinct categories and identify potential areas for filtering or aggregation.

In [28]:
# Identify categorical columns (object type)
categorical_cols = df.select_dtypes(include='object').columns

print("Unique values and their counts for categorical columns:")
for col in categorical_cols:
    print(f"\n--- Column: {col} ---")
    print(df[col].value_counts())

# Also check the 'Date Egg' column, which appears to be an object type but represents dates.
# It should ideally be converted to a datetime object for any time-series analysis or filtering by date.
print("\n--- Column: Date Egg ---")
print(df['Date Egg'].value_counts())

C:\Users\Thao Vy\AppData\Local\Temp\ipykernel_33968\3314448337.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

Unique values and their counts for categorical columns:

--- Column: studyName ---
studyName
PAL0910    120
PAL0809    114
PAL0708    110
Name: count, dtype: int64

--- Column: Species ---
Species
Adelie Penguin (Pygoscelis adeliae)          152
Gentoo penguin (Pygoscelis papua)            124
Chinstrap penguin (Pygoscelis antarctica)     68
Name: count, dtype: int64

--- Column: Region ---
Region
Anvers    344
Name: count, dtype: int64

--- Column: Island ---
Island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

--- Column: Stage ---
Stage
Adult, 1 Egg Stage    344
Name: count, dtype: int64

--- Column: Individual ID ---
Individual ID
N6A1      3
N6A2      3
N8A1      3
N8A2      3
N13A1     3
         ..
N98A2     1
N99A1     1
N99A2     1
N100A1    1
N100A2    1
Name: count, Length: 190, dtype: int64

--- Column: Clutch Completion ---
Clutch Completion
Yes    308
No      36
Name: count, dtype: int64

--- Column: Date Egg ---
Date Egg
2007-11-27    18
2007-11-16    16
2008-11-09    16
2009-11-18    14
2008-11-06    12
2008-11-13    12
2009-11-21    12
2008-11-04    12
2008-11-14    10
2009-11-15    10
2009-11-17    10
2009-11-22    10
2009-11-16    10
2007-11-29    10
2009-11-27    10
2007-11-09     8
2007-11-12     8
2008-11-08     8
2008-11-03     8
2009-12-01     8
2007-11-28     8
2008-11-24     8
2007-11-13     6
2008-11-02     6
2009-11-20     6
2009-11-23     6
2007-12-03     6
2009-11-25     6
2007-11-15     4
2007-11-10     4
2007-11-19     4
2008-11-15     4
2008-11-11     4
2008-11-17     4
2009-11-09     4
2009-11-10     4
2009-11-13     4
2007-11-26     4
2007-11-21     4
2007-11-30     4
2008-11-25     4
2007-11-11     2
2008-11-07     2
2008-11-05     2
2008-11-10     2
2009-11-12     2
2009-11-14     2
2007-11-18     2
2007-11-22     2
2009-11-19     2
Name: count, dtype: int64

--- Column: Sex ---
Sex
MALE      168
FEMALE    165
Name: count, dtype: int64

--- Column: Date Egg ---
Date Egg
2007-11-27    18
2007-11-16    16
2008-11-09    16
2009-11-18    14
2008-11-06    12
2008-11-13    12
2009-11-21    12
2008-11-04    12
2008-11-14    10
2009-11-15    10
2009-11-17    10
2009-11-22    10
2009-11-16    10
2007-11-29    10
2009-11-27    10
2007-11-09     8
2007-11-12     8
2008-11-08     8
2008-11-03     8
2009-12-01     8
2007-11-28     8
2008-11-24     8
2007-11-13     6
2008-11-02     6
2009-11-20     6
2009-11-23     6
2007-12-03     6
2009-11-25     6
2007-11-15     4
2007-11-10     4
2007-11-19     4
2008-11-15     4
2008-11-11     4
2008-11-17     4
2009-11-09     4
2009-11-10     4
2009-11-13     4
2007-11-26     4
2007-11-21     4
2007-11-30     4
2008-11-25     4
2007-11-11     2
2008-11-07     2
2008-11-05     2
2008-11-10     2
2009-11-12     2
2009-11-14     2
2007-11-18     2
2007-11-22     2
2009-11-19     2
Name: count, dtype: int64

Based on the unique values:

*   **'Species'**: This is a key categorical variable that will likely be used for grouping or analysis. We might filter for specific species or aggregate metrics by species.
*   **'Region'**, **'Island'**: These also look like good candidates for grouping or filtering, depending on the analysis goals.
*   **'Stage'**, **'Clutch Completion'**, **'Sex'**: These are fairly clean and can be used directly or for filtering.
*   **'studyName'**, **'Individual ID'**: These columns have many unique values, almost one per row. 'Individual ID' is an identifier and is likely not useful for direct analysis or aggregation unless we need to track specific individuals. 'studyName' has only a few unique values, so it could potentially be used for grouping or filtering if there are differences across studies.
*   **'Date Egg'**: This column is currently an `object` type. It should be converted to a `datetime` object to enable time-based filtering or aggregation (e.g., daily, monthly counts).

In [29]:
# Convert 'Date Egg' to datetime
df['Date Egg'] = pd.to_datetime(df['Date Egg'])

# Verify the conversion
print("\n--- After converting 'Date Egg' to datetime ---")
print(df['Date Egg'].dtype)
print(df.info())

--- After converting 'Date Egg' to datetime ---
datetime64[us]
<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   studyName            344 non-null    str
 1   Sample Number        344 non-null    int64
 2   Species              344 non-null    str
 3   Region               344 non-null    str
 4   Island               344 non-null    str
 5   Stage                344 non-null    str
 6   Individual ID        344 non-null    str
 7   Clutch Completion    344 non-null    str
 8   Date Egg             344 non-null    datetime64[us]
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  333 non-null    str
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    float64
dtypes: datetime64[us](1), float64(6), int64(1), str(8)
memory usage: 71.8 KB
None

Drop the 2 rows where ALL numeric measurements are missing and are commented as "Adult not sampled"

In [30]:
features_cols = [
    "Culmen Length (mm)",
    "Culmen Depth (mm)",
    "Flipper Length (mm)",
    "Sex",
    "Body Mass (g)",
    "Delta 15 N (o/oo)",
    "Delta 13 C (o/oo)",
]

df = df.dropna(subset=features_cols, how="all").copy()

At this point, the need for further filtering or aggregation depends entirely on the specific questions we want to answer. We've cleaned up missing values and ensured `Date Egg` is in the correct format.

**Possible next steps for filtering/aggregation could include:**

1.  **Filtering by Species or Island**: If we want to analyze a specific group of penguins.
2.  **Aggregating by Species, Island, or Date**: To see average culmen lengths, body masses, etc., for different groups or over time.
3.  **Feature Engineering**: Extracting year, month, or day from 'Date Egg' for time-series analysis.

To illustrate the process of aggregation, we will calculate the average values ​​of key physical attributes (beak length, beak depth, fin length, and body mass) for each penguin species on each island. This helps us better understand the differences between species and the influence of habitat.

In [31]:
# Aggregation Example: Calculate mean physical attributes by Species and Island
agg_df = df.groupby(['Species', 'Island'])[['Culmen Length (mm)', 'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)']].mean().reset_index()

print("Mean physical attributes by Species and Island:")
display(agg_df)

# Another example: Count the number of penguins by Species and Island
count_df = df.groupby(['Species', 'Island']).size().reset_index(name='Count')
print("\nNumber of penguins by Species and Island:")
display(count_df)

Mean physical attributes by Species and Island:

,Species,Island,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g)
0,Adelie Penguin (Pygoscelis adeliae),Biscoe,38.975000,18.370455,188.795455,3709.659091
1,Adelie Penguin (Pygoscelis adeliae),Dream,38.501786,18.251786,189.732143,3688.392857
2,Adelie Penguin (Pygoscelis adeliae),Torgersen,38.950980,18.429412,191.196078,3706.372549
3,Chinstrap penguin (Pygoscelis antarctica),Dream,48.833824,18.420588,195.823529,3733.088235
4,Gentoo penguin (Pygoscelis papua),Biscoe,47.504878,14.982114,217.186992,5076.016260

Number of penguins by Species and Island:

                                     Species     Island  Count
0        Adelie Penguin (Pygoscelis adeliae)     Biscoe     44
1        Adelie Penguin (Pygoscelis adeliae)      Dream     56
2        Adelie Penguin (Pygoscelis adeliae)  Torgersen     51
3  Chinstrap penguin (Pygoscelis antarctica)      Dream     68
4          Gentoo penguin (Pygoscelis papua)     Biscoe    123

Let's explore other aggregation techniques to gain a more comprehensive view of the data, including descriptive statistics such as minimum, maximum, median, and standard deviation, as well as counting the number of unique values.

In [32]:
# Aggregation Example: Calculate min, max, median, and std deviation of physical attributes by Species and Island
agg_stats_df = df.groupby(['Species', 'Island'])[['Culmen Length (mm)', 'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)']].agg(['min', 'max', 'median', 'std']).reset_index()

print("Min, Max, Median, and Std Deviation of physical attributes by Species and Island:")
display(agg_stats_df)

Min, Max, Median, and Std Deviation of physical attributes by Species and Island:

                                     Species     Island Culmen Length (mm)  \
                                                                       min
0        Adelie Penguin (Pygoscelis adeliae)     Biscoe               34.5
1        Adelie Penguin (Pygoscelis adeliae)      Dream               32.1
2        Adelie Penguin (Pygoscelis adeliae)  Torgersen               33.5
3  Chinstrap penguin (Pygoscelis antarctica)      Dream               40.9
4          Gentoo penguin (Pygoscelis papua)     Biscoe               40.9

                         Culmen Depth (mm)                         \
    max median       std               min   max median       std
0  45.6  38.70  2.480916              16.0  21.1  18.45  1.188820
1  44.1  38.55  2.465359              15.5  21.2  18.40  1.133617
2  46.0  38.90  3.025318              15.9  21.5  18.40  1.339447
3  58.0  49.55  3.339256              16.4  20.8  18.45  1.135395
4  59.6  47.30  3.081857              13.1  17.3  15.00  0.981220

  Flipper Length (mm)                         Body Mass (g)                  \
                  min    max median       std           min     max  median
0               172.0  203.0  189.5  6.729247        2850.0  4775.0  3750.0
1               178.0  208.0  190.0  6.585083        2900.0  4650.0  3575.0
2               176.0  210.0  191.0  6.232238        2900.0  4700.0  3700.0
3               178.0  212.0  196.0  7.131894        2700.0  4800.0  3700.0
4               203.0  231.0  216.0  6.484976        3950.0  6300.0  5000.0


          std
0  487.733722
1  455.146437
2  445.107940
3  384.335081
4  504.116237

Counting the number of unique values ​​('Individual ID') within each Species and Island group can help us understand the diversity of the recorded individuals.

In [33]:
# Aggregation Example: Count unique Individual IDs by Species and Island
unique_id_count_df = df.groupby(['Species', 'Island'])['Individual ID'].nunique().reset_index(name='Unique Individual IDs')

print("Number of unique Individual IDs by Species and Island:")
display(unique_id_count_df)

Number of unique Individual IDs by Species and Island:

                                     Species     Island  Unique Individual IDs
0        Adelie Penguin (Pygoscelis adeliae)     Biscoe                     44
1        Adelie Penguin (Pygoscelis adeliae)      Dream                     56
2        Adelie Penguin (Pygoscelis adeliae)  Torgersen                     51
3  Chinstrap penguin (Pygoscelis antarctica)      Dream                     58
4          Gentoo penguin (Pygoscelis papua)     Biscoe                     94

You can filter the DataFrame to include only records of a specific penguin species.

In [34]:
# Filtering Example: Filter by a specific Species
adelie_penguins = df[df['Species'] == 'Adelie Penguin (Pygoscelis adeliae)']

print("Data for Adelie Penguins:")
display(adelie_penguins.head())

Data for Adelie Penguins:

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo)
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426
5,PAL0708,6,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A2,Yes,2007-11-16,39.3,20.6,190.0,3650.0,MALE,8.66496,-25.29805

Additionally, we can filter the data based on an arithmetic condition, such as 'Culmen Length (mm)' being greater than 50mm. This allows us to focus on penguins with longer beaks.

In [35]:
# Filtering Example: Filter by a specific Island
gentoo_penguins = df[df['Species'] == 'Gentoo penguin (Pygoscelis papua)']

print("Data for Gentoo Penguins:")
display(gentoo_penguins.head())

# Filtering Example: Filter by a numerical condition (e.g., Culmen Length > 50mm)
long_culmen_penguins = df[df['Culmen Length (mm)'] > 50]

print("\nPenguins with Culmen Length > 50mm:")
display(long_culmen_penguins.head())

Data for Gentoo Penguins:

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo)
152,PAL0708,1,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N31A1,Yes,2007-11-27,46.1,13.2,211.0,4500.0,FEMALE,7.99300,-25.51390
153,PAL0708,2,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N31A2,Yes,2007-11-27,50.0,16.3,230.0,5700.0,MALE,8.14756,-25.39369
154,PAL0708,3,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N32A1,Yes,2007-11-27,48.7,14.1,210.0,4450.0,FEMALE,8.14705,-25.46172
155,PAL0708,4,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N32A2,Yes,2007-11-27,50.0,15.2,218.0,5700.0,MALE,8.25540,-25.40075
156,PAL0708,5,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N33A1,Yes,2007-11-18,47.6,14.5,215.0,5400.0,MALE,8.23450,-25.54456

Penguins with Culmen Length > 50mm:

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo)
172,PAL0708,21,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N41A1,Yes,2007-11-27,50.2,14.3,218.0,5700.0,MALE,7.89620,-25.37746
185,PAL0708,34,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N56A2,Yes,2007-12-03,59.6,17.0,230.0,6050.0,MALE,7.76843,-25.68210
196,PAL0809,45,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N8A1,Yes,2008-11-03,50.5,15.9,222.0,5550.0,MALE,8.46894,-26.60436
199,PAL0809,48,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N11A2,No,2008-11-09,50.5,15.9,225.0,5400.0,MALE,8.65803,-26.57585
205,PAL0809,54,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N14A2,Yes,2008-11-04,50.1,15.0,225.0,5000.0,MALE,8.50153,-26.61414

Finally, we can combine multiple conditions to filter more complex data. For example, we can search for female penguins of the species 'Adelie Penguin (Pygoscelis adeliae)' and from 'Biscoe' Island.

In [36]:
# Filtering Example: Filter by multiple conditions (e.g., Species and Sex and Island)
ad_fem_biscoe_penguins = df[(df['Species'] == 'Adelie Penguin (Pygoscelis adeliae)') &
                            (df['Sex'] == 'FEMALE') &
                            (df['Island'] == 'Biscoe')]

print("\nFemale Adelie Penguins from Biscoe Island:")
display(ad_fem_biscoe_penguins.head())

Female Adelie Penguins from Biscoe Island:

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo)
20,PAL0708,21,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N11A1,Yes,2007-11-12,37.8,18.3,174.0,3400.0,FEMALE,8.73762,-25.09383
22,PAL0708,23,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N12A1,Yes,2007-11-12,35.9,19.2,189.0,3800.0,FEMALE,9.22286,-25.03474
25,PAL0708,26,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N13A2,Yes,2007-11-10,35.3,18.9,187.0,3800.0,FEMALE,9.21292,-24.36130
27,PAL0708,28,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N17A2,Yes,2007-11-12,40.5,17.9,187.0,3200.0,FEMALE,8.08138,-25.49448
28,PAL0708,29,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N18A1,No,2007-11-10,37.9,18.6,172.0,3150.0,FEMALE,8.38404,-25.19837

We can use isin() to filter for complex conditions

In [37]:
# Filtering Example: Filter by multiple species using isin()
selected_species = ['Adelie Penguin (Pygoscelis adeliae)', 'Gentoo penguin (Pygoscelis papua)']
multi_species_penguins = df[df['Species'].isin(selected_species)]

print("\nPenguins from Adelie or Gentoo species:")
display(multi_species_penguins.head())

Penguins from Adelie or Gentoo species:

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo)
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426
5,PAL0708,6,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A2,Yes,2007-11-16,39.3,20.6,190.0,3650.0,MALE,8.66496,-25.29805

Rename all column for easier handling in following tasks

In [38]:
# Rename all columns
df = df.rename(columns={
    "Species": "species",
    "Island": "island",
    "Culmen Length (mm)": "bill_length_mm",
    "Culmen Depth (mm)": "bill_depth_mm",
    "Flipper Length (mm)": "flipper_length_mm",
    "Body Mass (g)": "body_mass_g",
    "Sex": "sex",
    "studyName": "study_name",
    "Sample Number": "sample_number",
    "Region": "region",
    "Stage": "stage",
    "Individual ID": "individual_id",
    "Clutch Completion": "clutch_completion",
    "Date Egg": "date_egg",
    "Delta 15 N (o/oo)": "delta_15_n",
    "Delta 13 C (o/oo)": "delta_13_c",
    "Comments": "comments" 
})

Save preprocessed data

In [39]:
import os

if not os.path.exists('data'):
    os.makedirs('data')
df.to_csv('data/penguins_preprocessed.csv', index=False)
print("Saved at: data/penguins_preprocessed.csv")

Saved at: data/penguins_preprocessed.csv